### ISSUE TITLE
Multipart_request issue

### ISSUE THREAD

**Issue by Vaibhavi107** [awazgyawali/multipart_request#1]
Every time adding    multipart_request: ^0.1.1 to flutter app shows following error while running in ios simulator. How to overcome this issue please help out.
   [!] No podspec found for `multipart_request` in `.symlinks/plugins/multipart_request/ios`
![Screen Shot 2019-04-10 at 6 02 44 PM](https://user-images.githubusercontent.com/20337870/55879062-5c79aa00-5bbb-11e9-8744-a063c512edfc.png)

**Comment by awazgyawali** [comment]
As written on the readme file, its only supposed to work on android. If you want to use this feature use dio library. They have this functionality.
