### ISSUE TITLE
Error getting when uploading image to the server.

### ISSUE THREAD

**Issue by otcsourcecodes** [awazgyawali/multipart_request#3]
[  +46 ms] I/flutter (18890): Gallery image path : /data/user/0/com.app.eloi_app/cache/image_picker8880255229850809802.jpg
[  +50 ms] W/om.app.eloi_ap(18890): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light
greylist, reflection)
[   +2 ms] W/om.app.eloi_ap(18890): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist,
reflection)
[   +2 ms] W/om.app.eloi_ap(18890): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
[   +4 ms] D/Multipart(18890): File user_account_image has value
/data/user/0/com.app.eloi_app/cache/image_picker8880255229850809802.jpg
[   +3 ms] D/Multipart(18890): Header Authorization has value Bearer
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjgwMTk3YzRlZmZhNGEzMTE5ODQ4ZDIxNjJmOGFkOTEzNjU3OTk4ZTA1MDkxZGRhM2U5YmRjZTFhNGQzMDZjMz
ZlNWNhMGZiMGQ2YTBhNDk2In0.eyJhdWQiOiIyIiwianRpIjoiODAxOTdjNGVmZmE0YTMxMTk4NDhkMjE2MmY4YWQ5MTM2NTc5OThlMDUwOTFkZGEzZTliZGNlMWE0ZDMw
NmMzNmU1Y2EwZmIwZDZhMGE0OTYiLCJpYXQiOjE1ODA0NzkwMzksIm5iZiI6MTU4MDQ3OTAzOSwiZXhwIjoxNjEyMTAxNDM5LCJzdWIiOiIyMyIsInNjb3BlcyI6W119.F
d229prIaLPyz2JHKvJpgIRl6SQpN3pezfKQ8g6s_lR1GQlhk4iyXtM9I5NpgrgMPbU7gB4s_dhpY10N_Gco2-5Ux4_jOcgZMldjjSviEV-chvgXEm-6p-GJUs7zZG93K2U
801aAgxDESZ9xHLageLPGr7lRfnFup35tWgFG9KjMJb4Jqg-EP16GO4Am3b5lpygNqHF-6naz0sknxtmVXEDtzKK3l3-TCHXJYSwQ9OcnRTBc9FQiGoSnieGmPxKmsJ_7D
ZANZsMG-lcm6UaXFX6_UMwsurOk56RhIBT6hWMAsIhDWM6aK2ecrByscwnYvKPl2UID7tr1cnfa_LKPn7ClrS0QIFHII5DIuu7R248TESyLSoAjHZhi1x-J70AgzxSxz80
AxNQHryH9NkmUdKtkJLlPEEqAmFakjcUjNUAyJVniXdXjIIDsZ11W3ui5eYoz6LQs6yMk0GJ9HzcKQcJq3o_murFpUjhvvedH0KQguoNhIQ6zyIGw7oEB6noq3ymTXKBdG
tZByNXP3rx-Rr8alLC-sBvtPhIrlpo4n1SF2_X857OVefyDhNrNRaxYaT-rLDXvqsEt3mw_PfEG13XzxghRpcSleGcXMNX2ZxF6gsGYwULxqfbnqKLDHfIiPFSqrA02X94
MHWx0LKqW_-4T2wv1UpCX3_D6Ci5f3DY
[   +5 ms] D/Multipart(18890): Header Accept has value application/json
[+1093 ms] W/System.err(18890): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread.
Current thread: AsyncTask #5
[        ] W/System.err(18890):         at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
[        ] W/System.err(18890):         at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:683)
[        ] W/System.err(18890):         at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:77)
[        ] W/System.err(18890):         at
io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:379)
[        ] W/System.err(18890):         at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:190)
[        ] W/System.err(18890):         at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
[        ] W/System.err(18890):         at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
[        ] W/System.err(18890):         at
com.brainants.multipartrequest.MultipartRequestPlugin$1$1.onProgress(MultipartRequestPlugin.java:42)
[        ] W/System.err(18890):         at
com.brainants.multipartrequest.ProgressRequestBody$CountingSink.write(ProgressRequestBody.java:57)
[        ] W/System.err(18890):         at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
[        ] W/System.err(18890):         at okio.RealBufferedSink.writeAll(RealBufferedSink.java:107)
[   +6 ms] W/System.err(18890):         at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
[        ] W/System.err(18890):         at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
[        ] W/System.err(18890):         at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
[        ] W/System.err(18890):         at com.brainants.multipartrequest.ProgressRequestBody.writeTo(ProgressRequestBody.java:44)
[        ] W/System.err(18890):         at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
[        ] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[        ] W/System.err(18890):         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[        ] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[   +1 ms] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[        ] W/System.err(18890):         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[        ] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[        ] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[   +1 ms] W/System.err(18890):         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[        ] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[        ] W/System.err(18890):         at
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
[        ] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[        ] W/System.err(18890):         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[        ] W/System.err(18890):         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
[        ] W/System.err(18890):         at okhttp3.RealCall.execute(RealCall.java:92)
[        ] W/System.err(18890):         at com.brainants.multipartrequest.MultipartRequest.sendMultipartRequest(MultipartRequest.j
ava:43)
[        ] W/System.err(18890):         at
com.brainants.multipartrequest.MultipartRequestPlugin$1.doInBackground(MultipartRequestPlugin.java:39)
[        ] W/System.err(18890):         at
com.brainants.multipartrequest.MultipartRequestPlugin$1.doInBackground(MultipartRequestPlugin.java:34)
[        ] W/System.err(18890):         at android.os.AsyncTask$2.call(AsyncTask.java:333)
[        ] W/System.err(18890):         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[        ] W/System.err(18890):         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
[        ] W/System.err(18890):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] W/System.err(18890):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] W/System.err(18890):         at java.lang.Thread.run(Thread.java:764)``

**Comment by awazgyawali** [comment]
Fixed on 0.2.0.
