### ISSUE TITLE
Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2

### ISSUE THREAD

**Issue by irbismaestro** [awazgyawali/multipart_request#4]
I had used multipart_request and all was very good,but after upgrade to version flutter
v1.14.6 with api 28 ,prepared to AndroidX(gradle.properties android.useAndroidX=true
android.enableJetifier=true)

```
request.setUrl(widget.dburlupload);
  request.addFile("file", "${dir}/shopred.db");
  request.addHeaders( {"user-agent": "agentcis", "api": "1.0.0", "authkey": widget.basetoken,"cisuser":widget.user});
  resp.Response response =  request.send();`
```
`

> java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2
W/System.err(11927): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
W/System.err(11927): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:683)
W/System.err(11927): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:77)
W/System.err(11927): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:379)
W/System.err(11927): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:190)
W/System.err(11927): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
W/System.err(11927): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
W/System.err(11927): 	at com.brainants.multipartrequest.MultipartRequestPlugin$1$1.onProgress(MultipartRequestPlugin.java:42)
W/System.err(11927): 	at com.brainants.multipartrequest.ProgressRequestBody$CountingSink.write(ProgressRequestBody.java:57)
W/System.err(11927): 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
W/System.err(11927): 	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:107)
W/System.err(11927): 	at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
W/System.err(11927): 	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
W/System.err(11927): 	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
W/System.err(11927): 	at com.brainants.multipartrequest.ProgressRequestBody.writeTo(ProgressRequestBody.java:44)
W/System.err(11927): 	at

**Comment by awazgyawali** [comment]
Version 0.2.0 is live, fixes this issue.
