### ISSUE TITLE
No podspec found for 'multipart_request'

### ISSUE THREAD

**Issue by ravindrasingh-prog** [awazgyawali/multipart_request#5]
When i use multipart_request plugin getting issue In iOS
No podspec found for `multipart_request` in `.symlinks/plugins/multipart_request/ios`

**Comment by BEARlogin** [comment]
Same issue

**Comment by BEARlogin** [comment]
@awazgyawali what we have to do, to compile it on iOS?

**Comment by awazgyawali** [comment]
Guys if you check the description, it clearly says only on android.

**Comment by BEARlogin** [comment]
> Guys if you check the description, it clearly says only on android.

How we can disable it on iOS version? App can't compile if the package is in pubspec dependencies.

**Comment by BEARlogin** [comment]
@awazgyawali i made the PR solved the issue and added ios support https://github.com/awazgyawali/multipart_request/pull/6

**Comment by awazgyawali** [comment]
Version 0.3.0 solves this issue. Thanks @BEARlogin  for the PR.
