### ISSUE TITLE
AndroidX build error

### ISSUE THREAD

**Issue by idileepd** [awazgyawali/multipart_request#8]
Update this flutter package to AndroidX
After I upgrade this manually I get rid of this error.
![WhatsApp Image 2020-07-31 at 5 15 35 PM](https://user-images.githubusercontent.com/34201306/89098534-31e1df00-d406-11ea-9de4-2b4c94c7013c.jpeg)

**Comment by idileepd** [comment]
Fixed ::
Changed Local cached package
``` Flutter sdk\.pub-cache\hosted\pub.dartlang.org\multipart_request-0.3.0 ```

Step 1 :
``` Flutter sdk\.pub-cache\hosted\pub.dartlang.org\multipart_request-0.3.0\android\build.gradle ```
change :

``` compileSdkVersion 27 ```

with 
``` compileSdkVersion 28 ```

![image](https://user-images.githubusercontent.com/34201306/89101011-e5080380-d419-11ea-876e-f24d9a5dbf32.png)

Step 2: 
``` Flutter sdk\.pub-cache\hosted\pub.dartlang.org\multipart_request-0.3.0\android\gradle.properties ```
add these 2 lines

``` android.useAndroidX=true```
``` android.enableJetifier=true```

![image](https://user-images.githubusercontent.com/34201306/89101053-33b59d80-d41a-11ea-9a02-925220f16994.png)

**Comment by idileepd** [comment]
I am making this issue open until package updates

**Comment by awazgyawali** [comment]
Version 0.3.1 is live now.

**Comment by idileepd** [comment]
thanks
